[package]
name = "ksai_proc"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crossterm = "0.29.0"
io = "0.0.2"
libc = "0.2.178"
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
sysinfo = "0.37.2"
